### ISSUE TITLE
Docs: Feedback for Getting Started with Hazelcast Cloud

### ISSUE THREAD

**Issue by nakata1312** [hazelcast/cloud-docs#42]
Hi, I have some feedback about [this page](https://github.com/hazelcast/cloud-docs/edit/main/docs/modules/ROOT/pages/getting-started.adoc)

I have downloaded hazelcast-5.0.zip in windows,after unzip,execute bin/hz-start.bat,it is always showing starting hazelcast in console,what else should I do before start?
![image](https://user-images.githubusercontent.com/6916243/143211881-68515b74-44f2-4590-8a13-218669a3278b.png)

**Comment by JakeSCahill** [comment]
The sample clients have all been improved with the launch of Hazelcast Viridian Managed Services. We will close this issue for now. Please feel free to reopen if you try again and it doesn't work.

You can find a [tutorial](https://docs.hazelcast.com/cloud/get-started) in our docs.
