### ISSUE TITLE
Docs: Feedback for What is Hazelcast Cloud?

### ISSUE THREAD

**Issue by mdumandag** [hazelcast/cloud-docs#52]
Hi, I have some feedback about [this page](https://github.com/hazelcast/cloud-docs/edit/main/docs/modules/ROOT/pages/preface.adoc)

The link in the `Scalability and Flexibility` section does not exist.

![image](https://user-images.githubusercontent.com/29387993/169059495-2baf9e9a-be5a-4cbd-879b-bb39bf80fc0a.png)

**Comment by arav-k** [comment]
#58 fixed and created a pull request for this.

**Comment by JakeSCahill** [comment]
Fixed in #75
