### ISSUE TITLE
Docs: Feedback for Query Streams from Confluent Cloud

### ISSUE THREAD

**Issue by g-donev** [hazelcast/cloud-docs#83]
Hi, I have some feedback about [this page](https://github.com/hazelcast/cloud-docs/edit/main/tutorials/modules/ROOT/pages/create-materialized-view-from-kafka.adoc)

This Streaming Real-Time Data tutorial on Viridian cannot be completed because it requires Hazelcast Enterprise Edition in order to run hz-cli.

ERROR: SSL/TLS requires Hazelcast Enterprise Edition

![E6438EC2-4222-4524-8C88-314162F4103F_1_201_a](https://user-images.githubusercontent.com/32678835/204386262-f7377c22-dc21-4d7c-a605-4741e4f5dc5c.jpeg)

**Comment by angelasimms** [comment]
Hi @g-donev, Just skimming through the instructions. In the pre-requisites (Before You Begin). It mentions the following "You can follow the instructions for SQL in [Hazelcast Viridian Hello World](https://docs.hazelcast.com/cloud/get-started) until you see the SQL prompt.". This includes instructions for the SQL (CLI) with instructions for installing Hazelcast Enterprise. At the moment, this is buried in the detail so should be added to the main set of instructions. I'll work on this, including testing the full tutorial.

**Comment by angelasimms** [comment]
Hello World and Getting Started now updated with full details for installing CLI.
